version: '2'
services:
  db:
    image: rethinkdb:2.3.5

  api:
    build: api
    env_file: .env
    ports:
      - "8000:8000"

  worker:
    build: celery
    env_file: .env

  redis:
    image: redis:3.2.5

