version: '2'
services:
  db:
    image: rethinkdb:2.3.5
    ports:
      - "28015:28015"

  redis:
    image: redis:3.2.5

  api:
    build: api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  worker:
    build: api/celery
    env_file: .env
