apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    provider: redis
spec:
  type: LoadBalancer
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    provider: redis
