apiVersion: v1
kind: ReplicationController
metadata:
  name: rethinkdb
spec:
  replicas: 1
  selector:
    provider: rethinkdb
  template:
    metadata:
      labels:
        app: rethinkdb
        provider: rethinkdb
    spec:
      containers:
      - name: rethinkdb
        image: rethinkdb
        ports:
        - containerPort: 28015
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        awsElasticBlockStore:
          volumeID: "vol-7f637de5"
          fsType: ext4
