apiVersion: v1
kind: Service
metadata:
  name: spodeli-api
  labels:
    provider: spodeli-api
    heritage: helm
spec:
  type: ClusterIP
  ports:
  - name: spodeli-api
    port: 5001
    targetPort: 5001
    protocol: TCP
  selector:
    provider: spodeli-api
