apiVersion: v1
kind: ReplicationController
metadata:
  name: spodeli-frontend
  labels:
    provider: spodeli-frontend
spec:
  replicas: 1
  selector:
    provider: spodeli-frontend
  template:
    metadata:
      name: spodeli-frontend
      labels:
        provider: spodeli-frontend
    spec:
      containers:
      - name: spodeli-frontend
        image: keitaro/spodelinovosti-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        command: ["source", "/data/.env"]
