apiVersion: v1
kind: Service
metadata:
  name: spodeli-api
  labels:
    provider: spodeli-api
    heritage: helm
spec:
  type: LoadBalancer
  ports:
  - name: spodeli-api
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    provider: spodeli-api
