apiVersion: v1
kind: ReplicationController
metadata:
  name: spodeli-api
  labels:
    provider: spodeli-api
spec:
  replicas: 1
  selector:
    provider: spodeli-api
  template:
    metadata:
      name: spodeli-api
      labels:
        provider: spodeli-api
    spec:
      containers:
      - name: spodeli-api
        image: keitaro/spodelinovosti-api
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: RDB_HOST
          value: "rethinkdb"
        - name: BROKER_URL
          value: "redis://redis:6379/0"
          
